service: sls-ts-sample

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: ap-northeast-1

functions:
  hello:
    handler: handler.hello
    events:
       - http:
           path: hello
           method: get
           cors: true
