service: sls-ts-sample

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: ap-northeast-1
  apiKeys:
    - internal

plugins:
  - serverless-webpack

functions:
  hello:
    handler: index.hello
    events:
       - http:
          path: hello
          method: get
          private: true
