service: sls-ts-sample

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: ap-northeast-1
  environment:
    PERMITTED_IPS: "any"

plugins:
  - serverless-webpack

package:
  include:
    - node_modules/**

functions:
  hello:
    handler: index.hello
    events:
       - http:
          path: hello
          method: get
